# Information on BART employment.

import pandas as pd

df = pd.read_csv('data/in/salaries.csv', usecols=['Position', 'MinPositionSalary', 'TotalWages', 'TotalRetirementAndHealthContribution'])
# Filter to jobs with full payouts
df = df.loc[df.TotalWages >= df.MinPositionSalary]
df.drop(columns='MinPositionSalary', inplace=True)
print('Total:', len(df.index))

# Classify by jobs that pay more than Bay Area median
median_income = 137000
df.insert(2, 'high_paying', df.TotalWages > median_income)
hp_count = len(df.loc[df.high_paying].index)
print('High-paying:', hp_count, '(' + str(round(hp_count / len(df.index) * 100)) + '%)')

print('Mean salary:', df.TotalWages.mean())
print('Median salary:', df.TotalWages.median())

category_map = {
    # Administrative and Clerical Support
    'Administrative Analyst - Boa': 'Administrative and Clerical Support',
    'Administrative Analyst NR': 'Administrative and Clerical Support',
    'Administrative Analyst SEIU': 'Administrative and Clerical Support',
    'Administrative Coordinator': 'Administrative and Clerical Support',
    'Administrative Support Officer': 'Administrative and Clerical Support',
    'Administrative Technician SEIU': 'Administrative and Clerical Support',
    'Assistant Admin Analyst - SEIU': 'Administrative and Clerical Support',
    'Computer Support Coordinator': 'Administrative and Clerical Support',
    'Customer Service Clerk': 'Administrative and Clerical Support',
    'Executive Assistant': 'Administrative and Clerical Support',
    'Mail Services Supervisor': 'Administrative and Clerical Support',
    'Receptionist': 'Administrative and Clerical Support',
    'Records and Supply Technician': 'Administrative and Clerical Support',
    'Reprographics Equipment Oper': 'Administrative and Clerical Support',
    'Senior Clerk SEIU': 'Administrative and Clerical Support',
    'Senior Computer Support Coord': 'Administrative and Clerical Support',
    'Senior Mail Services Support Clerk': 'Administrative and Clerical Support',
    'Senior Transportation Training Clerk': 'Administrative and Clerical Support',

    # Executive Leadership and Administration
        'Assistant GM Performance & Budget': 'Executive Leadership and Administration',
    'Chief Of Staff': 'Executive Leadership and Administration',
    'Deputy General Manager': 'Executive Leadership and Administration',
    'General Manager': 'Executive Leadership and Administration',
    'Assistant GM Operations': 'Executive Leadership and Administration',
    'Assistant GM Technology': 'Executive Leadership and Administration',
    'Assistant GM Planning and Development': 'Executive Leadership and Administration',
    'Assistant GM Performance and Budget': 'Executive Leadership and Administration',
    'Assistant GM, External Affairs': 'Executive Leadership and Administration',
    'Assistant GM, Infrastructure Delivery': 'Executive Leadership and Administration',
    'Assistant GM Finance, Interim': 'Executive Leadership and Administration',
    'Chief Communications Officer': 'Executive Leadership and Administration',
    'Chief Infrastructure Delivery Officer': 'Executive Leadership and Administration',
    'Chief Mechanical Officer': 'Executive Leadership and Administration',
    'Chief Safety Officer': 'Executive Leadership and Administration',
    'Chief Transportation Officer': 'Executive Leadership and Administration',
    'Director': 'Executive Leadership and Administration',
    'Director Of Budgets': 'Executive Leadership and Administration',
    'Director Of Customer Access': 'Executive Leadership and Administration',
    'Director Of Financial Planning': 'Executive Leadership and Administration',
    'Director Of Fire Life Safety': 'Executive Leadership and Administration',
    'Director Of Government And Comm Relations': 'Executive Leadership and Administration',
    'Director Of Human Resources': 'Executive Leadership and Administration',
    'Director Of Labor Relations': 'Executive Leadership and Administration',
    'Director Of Marketing And Research': 'Executive Leadership and Administration',
    'Director Of Operations Planning': 'Executive Leadership and Administration',
    'Director Of Performance And Audit': 'Executive Leadership and Administration',
    'Director Of Procurement': 'Executive Leadership and Administration',
    'Director Of Real Estate and Prop Management.': 'Executive Leadership and Administration',
    'Director Of Risk And Insurance Management.': 'Executive Leadership and Administration',
    'Director Of Security Programs': 'Executive Leadership and Administration',
    'Director Of Technology': 'Executive Leadership and Administration',
    'Director Of Funding Strategy': 'Executive Leadership and Administration',
    'Deputy Director Of Human Resources': 'Executive Leadership and Administration',
    'Managing Director Cap Corridor': 'Executive Leadership and Administration',
    'Deputy Managing Director Cap Cor': 'Executive Leadership and Administration',
    'Independent Police Auditor': 'Executive Leadership and Administration',
    'Independent Police Administrator': 'Executive Leadership and Administration',
    'Deputy Inspector General': 'Executive Leadership and Administration',
    'Assistant Chief Infrastructure Delivery Office': 'Executive Leadership and Administration',
    'Assistant GM Planning & Development': 'Executive Leadership and Administration',
    'Director Of Real Estate & Prop Management.': 'Executive Leadership and Administration',
    'Manager. Of Accredited And Support Service': 'Executive Leadership and Administration',
    'Manager Of Internal Audit': 'Executive Leadership and Administration',
    'Manager Of Special Projects': 'Executive Leadership and Administration',
    'Senior Manager Performance & Innovation': 'Executive Leadership and Administration',

    # Finance, Accounting, and Budget
    'Accountant': 'Finance, Accounting, and Budget',
    'Accounting Analyst': 'Finance, Accounting, and Budget',
    'Accounting Supervisor': 'Finance, Accounting, and Budget',
    'Assistant Treasurer': 'Finance, Accounting, and Budget',
    'Assistant Treasury Analyst': 'Finance, Accounting, and Budget',
    'Cash Handler': 'Finance, Accounting, and Budget',
    'Cash Handling Electronic Technician': 'Finance, Accounting, and Budget',
    'Cash Handling Fore worker': 'Finance, Accounting, and Budget',
    'Director Of Financial Planning': 'Finance, Accounting, and Budget',
    'Financial Analyst I': 'Finance, Accounting, and Budget',
    'Financial Analyst II': 'Finance, Accounting, and Budget',
    'Junior Accountant': 'Finance, Accounting, and Budget',
    'Liability Risk Analyst': 'Finance, Accounting, and Budget',
    'Manager. Of Accounting': 'Finance, Accounting, and Budget',
    'Manager. Of Budget and Admin, Cap Cor': 'Finance, Accounting, and Budget',
    'Manager. Of Comp and Analytics': 'Finance, Accounting, and Budget',
    'Manager. Of Financial Planning': 'Finance, Accounting, and Budget',
    'Manager Of Operating Budgets': 'Finance, Accounting, and Budget',
    'Manager Of Revenue Control': 'Finance, Accounting, and Budget',
    'Principal Financial Analyst': 'Finance, Accounting, and Budget',
    'Senior Accounting Analyst': 'Finance, Accounting, and Budget',
    'Senior Financial Analyst AFSCME': 'Finance, Accounting, and Budget',
    'Senior Manager Of Finance': 'Finance, Accounting, and Budget',
    'Strategic Budget Administrator': 'Finance, Accounting, and Budget',
    'Insurance Analyst': 'Finance, Accounting, and Budget',
    'Manager. Of Budget & Admin, Cap Cor': 'Finance, Accounting, and Budget',
    'Manager. Of Comp & Analytics': 'Finance, Accounting, and Budget',

    # Human Resources, Labor, and Workforce Development
    'Director Of Human Resources': 'Human Resources, Labor, and Workforce Development',
    'Director Of Labor Relations': 'Human Resources, Labor, and Workforce Development',
    'Employee Development Specialist Sa': 'Human Resources, Labor, and Workforce Development',
    'Employee Development Specialist SEIU': 'Human Resources, Labor, and Workforce Development',
    'Employee Development Specialist To': 'Human Resources, Labor, and Workforce Development',
    'Equity Programs Administrator': 'Human Resources, Labor, and Workforce Development',
    'HR Project Administrator': 'Human Resources, Labor, and Workforce Development',
    'Human Resources Analyst I': 'Human Resources, Labor, and Workforce Development',
    'Human Resources Analyst II': 'Human Resources, Labor, and Workforce Development',
    'Human Resources Specialist': 'Human Resources, Labor, and Workforce Development',
    'Human Resources Specialist LT': 'Human Resources, Labor, and Workforce Development',
    'Instructional Design and Sys Adm': 'Human Resources, Labor, and Workforce Development',
    'Labor Relations Rep I': 'Human Resources, Labor, and Workforce Development',
    'Manager. Of Absence Management.': 'Human Resources, Labor, and Workforce Development',
    'Manager Of Leave Programs': 'Human Resources, Labor, and Workforce Development',
    'Manager Of Labor Relations': 'Human Resources, Labor, and Workforce Development',
    'Manager Of Substance Abuse Program': 'Human Resources, Labor, and Workforce Development',
    'Manager Of Workforce Development': 'Human Resources, Labor, and Workforce Development',
    'Principal Benefits Analyst': 'Human Resources, Labor, and Workforce Development',
    'Principal Class and Comp Analyst': 'Human Resources, Labor, and Workforce Development',
    'Principal Labor Relations Rep': 'Human Resources, Labor, and Workforce Development',
    'Principal Recruiter': 'Human Resources, Labor, and Workforce Development',
    'Senior Human Resources Specialist': 'Human Resources, Labor, and Workforce Development',
    'Senior Labor Relations Rep': 'Human Resources, Labor, and Workforce Development',
    'Senior Leave Management Analyst': 'Human Resources, Labor, and Workforce Development',
    'Senior Manager Of Contract Labor Compliance': 'Human Resources, Labor, and Workforce Development',
    'Senior Manager Of Econ Oppy Policies': 'Human Resources, Labor, and Workforce Development',
    'Senior Manager Of Work Force Policy Compliance': 'Human Resources, Labor, and Workforce Development',
    'Senior Recruiter': 'Human Resources, Labor, and Workforce Development',
    'Senior Time and Labor Admin Analyst': 'Human Resources, Labor, and Workforce Development',
    'Supervisor Of HRIS': 'Human Resources, Labor, and Workforce Development',
    'Supervisor Of Leave Management': 'Human Resources, Labor, and Workforce Development',
    'Supervisor Of Recruiting': 'Human Resources, Labor, and Workforce Development',
    'Supervisor Of Workforce Development': 'Human Resources, Labor, and Workforce Development',
    'Time And Labor Admin Analyst': 'Human Resources, Labor, and Workforce Development',
    'Time and Labor Admin Analyst Atu': 'Human Resources, Labor, and Workforce Development',
    'Workforce Development Administrator': 'Human Resources, Labor, and Workforce Development',
    'Senior Workforce Development Analyst': 'Human Resources, Labor, and Workforce Development',
    'Instructional Design & Sys Adm': 'Human Resources, Labor, and Workforce Development',
    'Manager Of Talent Acquisition': 'Human Resources, Labor, and Workforce Development',
    'Manager Of Time And Admin': 'Human Resources, Labor, and Workforce Development',
    'Manager Of Ops Training And Development': 'Human Resources, Labor, and Workforce Development',
    'Principal Admin Analyst AFSCME': 'Human Resources, Labor, and Workforce Development',
    'Principal Class & Comp Analyst': 'Human Resources, Labor, and Workforce Development',
    'Senior Admin Analyst  AFSCME': 'Human Resources, Labor, and Workforce Development',
    'Senior HRIS Analyst': 'Human Resources, Labor, and Workforce Development',
    'Senior Time & Labor Admin Analyst': 'Human Resources, Labor, and Workforce Development',
    'Time & Labor Admin Analyst Atu': 'Human Resources, Labor, and Workforce Development',

    # Legal, Government, and Compliance
    'Associate General Counsel': 'Legal, Government, and Compliance',
    'Attorney I': 'Legal, Government, and Compliance',
    'Attorney II': 'Legal, Government, and Compliance',
    'Attorney III': 'Legal, Government, and Compliance',
    'Board Analyst': 'Legal, Government, and Compliance',
    'Contract Administrator': 'Legal, Government, and Compliance',
    'Contract Specialist II': 'Legal, Government, and Compliance',
    'Contract Specialist III': 'Legal, Government, and Compliance',
    'Deputy Assistant District Secretary': 'Legal, Government, and Compliance',
    'District Secretary': 'Legal, Government, and Compliance',
    'Assistant District Secretary': 'Legal, Government, and Compliance',
    'Legal Administrative Analyst': 'Legal, Government, and Compliance',
    'Manager Of Government Rel and Leg Affairs': 'Legal, Government, and Compliance',
    'Manager Of Local Govt and Com Rel': 'Legal, Government, and Compliance',
    'Manager. Of Contract Administration': 'Legal, Government, and Compliance',
    'Manager. Of Contract Compliance': 'Legal, Government, and Compliance',
    'Paralegal': 'Legal, Government, and Compliance',
    'Principal Contract Specialist': 'Legal, Government, and Compliance',
    'Principal Gov and Comm Rel Rep': 'Legal, Government, and Compliance',
    'Principal Grants Officer': 'Legal, Government, and Compliance',
    'Principal Internal Auditor': 'Legal, Government, and Compliance',
    'Principal Property Development Ofc': 'Legal, Government, and Compliance',
    'Senior Board Analyst': 'Legal, Government, and Compliance',
    'Senior Legal Secretary': 'Legal, Government, and Compliance',
    'Senior Title Vi and Enviro Jus Analyst': 'Legal, Government, and Compliance',
    'Stakeholder Engagement Administration': 'Legal, Government, and Compliance',
    'Insp Gen Investigative Auditor': 'Legal, Government, and Compliance',
    'Manager Of Local Govt & Com Rel': 'Legal, Government, and Compliance',
    'Manager. Of Government Rel & Leg Affairs': 'Legal, Government, and Compliance',
    'Manager. Of Grants & Funding Advocate': 'Legal, Government, and Compliance',
    'Principal Gov & Comm Rel Rep': 'Legal, Government, and Compliance',
    'Senior Attorney': 'Legal, Government, and Compliance',
    'Senior Title Vi & Enviro Jus Analyst': 'Legal, Government, and Compliance',

    # Communications, Marketing, and Public Affairs
    'Communication Coordinator': 'Communications, Marketing, and Public Affairs',
    'Communications Officer': 'Communications, Marketing, and Public Affairs',
    'Communications Specialist': 'Communications, Marketing, and Public Affairs',
    'Director Of Marketing And Research': 'Communications, Marketing, and Public Affairs',
    'Manager Of Marketing': 'Communications, Marketing, and Public Affairs',
    'Manager Of Media Relations': 'Communications, Marketing, and Public Affairs',
    'Manager. Of Ad Franchise Program': 'Communications, Marketing, and Public Affairs',
    'Manager. Of Cap Corr Market/Comm': 'Communications, Marketing, and Public Affairs',
    'Multimedia Producer': 'Communications, Marketing, and Public Affairs',
    'Principal Marketing Rep': 'Communications, Marketing, and Public Affairs',
    'Senior Graphic Artist': 'Communications, Marketing, and Public Affairs',
    'Senior Gov and Comm Relations Rep': 'Communications, Marketing, and Public Affairs',
    'Senior Marketing Rep': 'Communications, Marketing, and Public Affairs',
    'Senior Gov & Comm Relations Rep': 'Communications, Marketing, and Public Affairs',

    # Police, Security, and Safety
    'Community Services Officer': 'Police, Security, and Safety',
    'Crisis Intervention Specialist': 'Police, Security, and Safety',
    'Crime Analyst': 'Police, Security, and Safety',
    'Deputy Police Chief': 'Police, Security, and Safety',
    'Fare Inspection Officer': 'Police, Security, and Safety',
    'Fire Life Safety Program Admin': 'Police, Security, and Safety',
    'Fire Protection Fore worker': 'Police, Security, and Safety',
    'Fire Protection Worker': 'Police, Security, and Safety',
    'Fire Service Worker': 'Police, Security, and Safety',
    'Independent Police Invest': 'Police, Security, and Safety',
    'Lead Police Detective': 'Police, Security, and Safety',
    'Lead Police Dispatcher': 'Police, Security, and Safety',
    'Police Admin Specialist': 'Police, Security, and Safety',
    'Police Admin Supervisor': 'Police, Security, and Safety',
    'Police Chief': 'Police, Security, and Safety',
    'Police Civilian Supervisor Comm': 'Police, Security, and Safety',
    'Police Dispatcher': 'Police, Security, and Safety',
    'Police Lieutenant': 'Police, Security, and Safety',
    'Police Lieutenant (84 Hour)': 'Police, Security, and Safety',
    'Police Officer': 'Police, Security, and Safety',
    'Police Officer (84 Hour)': 'Police, Security, and Safety',
    'Police Officer In Academy': 'Police, Security, and Safety',
    'Police Sergeant': 'Police, Security, and Safety',
    'Police Sergeant (84 Hour)': 'Police, Security, and Safety',
    'Revenue Protection Guard': 'Police, Security, and Safety',
    'Revenue Protection Supervisor': 'Police, Security, and Safety',
    'Senior Ops Safety Spec': 'Police, Security, and Safety',
    'Senior Police Officer - Adv.': 'Police, Security, and Safety',
    'Senior Police Officer - Int.': 'Police, Security, and Safety',
    'Senior Police Officer-Adv. (84 Hour)': 'Police, Security, and Safety',
    'Senior Police Officer-Int. (84 Hour)': 'Police, Security, and Safety',
    'Senior Safety Specialist': 'Police, Security, and Safety',
    'Safety Management System Manager': 'Police, Security, and Safety',
    'Safety Specialist': 'Police, Security, and Safety',
    'Principal Ops Safety Spec': 'Police, Security, and Safety',
    'Principal Safety Engineer': 'Police, Security, and Safety',
    'Principal Safety Specialist': 'Police, Security, and Safety',
    'Quality Assurance Officer': 'Police, Security, and Safety',
    'Manager Of Operations Safety': 'Police, Security, and Safety',
    'Manager. Of Employee/Patron Safety': 'Police, Security, and Safety',
    'Manager. Of Engineer Safety': 'Police, Security, and Safety',
    'Police Tech Administrator': 'Police, Security, and Safety',
    'Supervisor Crisis Int & Outreach Pro': 'Police, Security, and Safety',

    # Engineering and Technical
    'AFC Electronic Technician': 'Engineering and Technical',
    'Assistant Chief Maintenance Officer': 'Engineering and Technical',
    'CAD Drafter': 'Engineering and Technical',
    'Computer Electronic Technician': 'Engineering and Technical',
    'Computer Systems Engineer': 'Engineering and Technical',
    'Cyber Security Engineer': 'Engineering and Technical',
    'Database Administrator': 'Engineering and Technical',
    'Document Config Controller': 'Engineering and Technical',
    'Document Control Specialist': 'Engineering and Technical',
    'Dump Truck/Equipment Operator': 'Engineering and Technical',
    'Electronics and Comm Engineer': 'Engineering and Technical',
    'Engineer': 'Engineering and Technical',
    'Junior Engineer': 'Engineering and Technical',
    'Junior Train Control Engineer': 'Engineering and Technical',
    'Maintenance Engineer': 'Engineering and Technical',
    'Manager Of Information Systems': 'Engineering and Technical',
    'Manager Of Mechanical Engr.': 'Engineering and Technical',
    'Manager Of System Integration': 'Engineering and Technical',
    'Manager Of Technology Programs': 'Engineering and Technical',
    'Manager Of Train Control Engineer': 'Engineering and Technical',
    'Manager. Of Civil and Structural Eng': 'Engineering and Technical',
    'Manager. Of Computer Sys Engineer': 'Engineering and Technical',
    'Manager. Of Cyber Security': 'Engineering and Technical',
    'Manager. Of Drafting, and Configuration': 'Engineering and Technical',
    'Manager. Of Electrical Engineer': 'Engineering and Technical',
    'Manager. Of Electronic and Communications Engineer': 'Engineering and Technical',
    'Principal Architect': 'Engineering and Technical',
    'Principal Civil Engineer': 'Engineering and Technical',
    'Principal Computer Systems Eng': 'Engineering and Technical',
    'Principal Electrical Engineer': 'Engineering and Technical',
    'Principal Engineer': 'Engineering and Technical',
    'Principal Fire Protect Eng': 'Engineering and Technical',
    'Principal Integration Engineer': 'Engineering and Technical',
    'Principal Mechanical Engineer': 'Engineering and Technical',
    'Principal Structural Engineer': 'Engineering and Technical',
    'Principal Track Engineer': 'Engineering and Technical',
    'Principal Train Contract Engineering': 'Engineering and Technical',
    'Principal Vehicle Sys Engineer': 'Engineering and Technical',
    'Project Manager': 'Engineering and Technical',
    'Project Manager, Accessibility': 'Engineering and Technical',
    'Project Manager, Construction': 'Engineering and Technical',
    'Project Manager, Extensions': 'Engineering and Technical',
    'Project Manager, Sys Integration': 'Engineering and Technical',
    'Project Support Manager': 'Engineering and Technical',
    'Records & Supply Technician': 'Engineering and Technical',
    'Research Projects Supervisor': 'Engineering and Technical',
    'Senior Applications Analyst': 'Engineering and Technical',
    'Senior Appl Programmer Analyst': 'Engineering and Technical',
    'Senior CAD Drafter': 'Engineering and Technical',
    'Senior Civil Engineer': 'Engineering and Technical',
    'Senior Computer Systems Engineer': 'Engineering and Technical',
    'Senior Construction Engineer': 'Engineering and Technical',
    'Senior Electrical Engineer': 'Engineering and Technical',
    'Senior Electronics and Comm Engineer': 'Engineering and Technical',
    'Senior Engineer': 'Engineering and Technical',
    'Senior Maintenance Engineer': 'Engineering and Technical',
    'Senior Mechanical Engineer': 'Engineering and Technical',
    'Senior Project Engineer': 'Engineering and Technical',
    'Senior Structural Engineer': 'Engineering and Technical',
    'Senior Telecommunications Tech': 'Engineering and Technical',
    'Senior Train Control Engineer': 'Engineering and Technical',
    'Senior Traction Power Engineer': 'Engineering and Technical',
    'Senior Vehicle Systems Engineer': 'Engineering and Technical',
    'Structural Engineer': 'Engineering and Technical',
    'System Service Fore Worker': 'Engineering and Technical',
    'Tech Publications Admin': 'Engineering and Technical',
    'Train Control Electronic Tech': 'Engineering and Technical',
    'Train Control Engineer': 'Engineering and Technical',
    'Transit Veh Electronic Technician': 'Engineering and Technical',
    'Vehicle Systems Engineer': 'Engineering and Technical',
    'Communications Electronic Tech': 'Engineering and Technical',
    'Dum Engineer': 'Engineering and Technical',
    'Electronics & Comm Engineer': 'Engineering and Technical',
    'It Project Manager': 'Engineering and Technical',
    'Manager Of Traction Power Engr': 'Engineering and Technical',
    'Manager Of Vehicle Sys Engineer': 'Engineering and Technical',
    'Manager. Of Civil & Structural Eng': 'Engineering and Technical',
    'Manager. Of Drafting & Configuration': 'Engineering and Technical',
    'Manager. Of Electronic & Communications Engineer': 'Engineering and Technical',
    'Power & Support Controller': 'Engineering and Technical',
    'Principal Construction Engr': 'Engineering and Technical',
    'Principal Electronic Comm Engineer': 'Engineering and Technical',
    'Principal Project Engineer': 'Engineering and Technical',
    'Senior Electronics & Comm Engineer': 'Engineering and Technical',
    'Senior Production Engineer': 'Engineering and Technical',
    'Train Control Fore Worker': 'Engineering and Technical',

    # Operations and Transportation
    'Actor Central Control': 'Operations and Transportation',
    'Actor Service Delivery': 'Operations and Transportation',
    'Assistant Chief Operations Officer': 'Operations and Transportation',
    'Crew Office Supervisor': 'Operations and Transportation',
    'Director Of Operations Planning': 'Operations and Transportation',
    'Dum System Rail Controller': 'Operations and Transportation',
    'Manager. Of Central Control': 'Operations and Transportation',
    'Manager Of Operations Reliability': 'Operations and Transportation',
    'Manager Of Schedules and Services': 'Operations and Transportation',
    'Manager Of Transportation Ops Support': 'Operations and Transportation',
    'Operations Fore Worker': 'Operations and Transportation',
    'Operations Planner': 'Operations and Transportation',
    'Operations Supervisor Liaison': 'Operations and Transportation',
    'Operations Training Supervisor': 'Operations and Transportation',
    'Principal Operations Planner': 'Operations and Transportation',
    'Rail Operations Controller': 'Operations and Transportation',
    'Rail Services Compliance Officer Capitol': 'Operations and Transportation',
    'Road Supervisor Of Engines': 'Operations and Transportation',
    'Scheduling Analyst': 'Operations and Transportation',
    'Scheduling Supervisor': 'Operations and Transportation',
    'Senior Cash Handler': 'Operations and Transportation',
    'Senior Operations Fore Worker': 'Operations and Transportation',
    'Senior Operations Supervisor Liaison': 'Operations and Transportation',
    'Senior Scheduling Analyst Atu': 'Operations and Transportation',
    'Station Agent': 'Operations and Transportation',
    'Train Operator': 'Operations and Transportation',
    'Transportation Adm Specialist': 'Operations and Transportation',
    'Transportation Supervisor': 'Operations and Transportation',
    'Transit Ambassador': 'Operations and Transportation',
    'Transit Information Clerk': 'Operations and Transportation',
    'Group Manager. Ops Support & Review': 'Operations and Transportation',
    'Manager Of Schedules & Services': 'Operations and Transportation',
    'Supervisor Business Systems Operations': 'Operations and Transportation',

    # Maintenance, Facilities, and Trades
    'AFC Fore worker': 'Maintenance, Facilities, and Trades',
    'Assistant Superintendent Of Power Mech Maintenance': 'Maintenance, Facilities, and Trades',
    'Assistant Superintendent Of Rests': 'Maintenance, Facilities, and Trades',
    'Assistant Superintendent Of Rests, Cap Cor': 'Maintenance, Facilities, and Trades',
    'Assistant Superintendent Of System Service': 'Maintenance, Facilities, and Trades',
    'Assistant Superintendent Of Systems Maintenance': 'Maintenance, Facilities, and Trades',
    'Assistant Superintendent Of Way and Facilities': 'Maintenance, Facilities, and Trades',
    'Auto and Equipment Fore worker': 'Maintenance, Facilities, and Trades',
    'Auto and Equipment Maintenance Supervisor': 'Maintenance, Facilities, and Trades',
    'Auto and Equipment Mechanic': 'Maintenance, Facilities, and Trades',
    'Buildings Fore worker': 'Maintenance, Facilities, and Trades',
    'Buildings Worker': 'Maintenance, Facilities, and Trades',
    'Central Maintenance Supervisor': 'Maintenance, Facilities, and Trades',
    'Comp Vehicle Maintenance Dum': 'Maintenance, Facilities, and Trades',
    'Electrical Fore worker': 'Maintenance, Facilities, and Trades',
    'Electrical Helper': 'Maintenance, Facilities, and Trades',
    'Electrical/Electrical-Mech Assembler II': 'Maintenance, Facilities, and Trades',
    'Electrician': 'Maintenance, Facilities, and Trades',
    'Elevator/Escalator Fore worker': 'Maintenance, Facilities, and Trades',
    'Elevator/Escalator Trainee': 'Maintenance, Facilities, and Trades',
    'Elevator/Escalator Worker': 'Maintenance, Facilities, and Trades',
    'ERS Fore worker': 'Maintenance, Facilities, and Trades',
    'ERS Technician': 'Maintenance, Facilities, and Trades',
    'Facilities Maintenance Supervisor': 'Maintenance, Facilities, and Trades',
    'Grounds Fore worker': 'Maintenance, Facilities, and Trades',
    'Grounds Worker': 'Maintenance, Facilities, and Trades',
    'Grounds Worker/Applicator': 'Maintenance, Facilities, and Trades',
    'Irrigation/Grounds Worker': 'Maintenance, Facilities, and Trades',
    'Locksmith': 'Maintenance, Facilities, and Trades',
    'Manager Of Maintenance Administration': 'Maintenance, Facilities, and Trades',
    'Manager Of Maintenance Plan and Logistics': 'Maintenance, Facilities, and Trades',
    'Manager Of Maintenance Support': 'Maintenance, Facilities, and Trades',
    'Manager Of Transit Vehicle Cleaning': 'Maintenance, Facilities, and Trades',
    'Manager. Of Auto and Equipment Maintenance': 'Maintenance, Facilities, and Trades',
    'Material Coordinator': 'Maintenance, Facilities, and Trades',
    'Painter': 'Maintenance, Facilities, and Trades',
    'Power and Mechanical Fore Worker': 'Maintenance, Facilities, and Trades',
    'Power and Mechanical Worker': 'Maintenance, Facilities, and Trades',
    'Rolling Stock Fore Worker': 'Maintenance, Facilities, and Trades',
    'Sect Manager Elev/Escalator Maintenance': 'Maintenance, Facilities, and Trades',
    'Sect Manager Power and Mech Maintenance': 'Maintenance, Facilities, and Trades',
    'Sect Manager Structures Maintenance': 'Maintenance, Facilities, and Trades',
    'Sect Manager Struct Insp and Maintenance': 'Maintenance, Facilities, and Trades',
    'Sect Manager Systems Maintenance': 'Maintenance, Facilities, and Trades',
    'Sect Manager Track Maintenance': 'Maintenance, Facilities, and Trades',
    'Senior Central Maintenance Supervisor': 'Maintenance, Facilities, and Trades',
    'Senior Logistics Supervisor': 'Maintenance, Facilities, and Trades',
    'Senior Maintenance Planner': 'Maintenance, Facilities, and Trades',
    'Senior Manager Of Infra Asset Management': 'Maintenance, Facilities, and Trades',
    'Senior Manager Of Maintenance Plan Sched': 'Maintenance, Facilities, and Trades',
    'Senior Manager Of Maintenance Support': 'Maintenance, Facilities, and Trades',
    'Senior Manager Of RSandS Ops Admin': 'Maintenance, Facilities, and Trades',
    'Senior Storekeeper': 'Maintenance, Facilities, and Trades',
    'Shop Scheduler': 'Maintenance, Facilities, and Trades',
    'Storekeeper': 'Maintenance, Facilities, and Trades',
    'Structures Equipment Operator': 'Maintenance, Facilities, and Trades',
    'Structures Fore Worker': 'Maintenance, Facilities, and Trades',
    'Structures Inspect Fore Worker': 'Maintenance, Facilities, and Trades',
    'Structures Inspector': 'Maintenance, Facilities, and Trades',
    'Structures Welder': 'Maintenance, Facilities, and Trades',
    'Structures Worker': 'Maintenance, Facilities, and Trades',
    'Superintendent Of Capital Construction': 'Maintenance, Facilities, and Trades',
    'Superintendent Of Power and Mech Maintenance': 'Maintenance, Facilities, and Trades',
    'Superintendent Of Rolling Stock and Shops': 'Maintenance, Facilities, and Trades',
    'Superintendent Of System Service': 'Maintenance, Facilities, and Trades',
    'Superintendent Of Systems Maintenance': 'Maintenance, Facilities, and Trades',
    'Superintendent Of Way and Facilities': 'Maintenance, Facilities, and Trades',
    'System Service Crew Leader': 'Maintenance, Facilities, and Trades',
    'System Service Supervisor': 'Maintenance, Facilities, and Trades',
    'System Service Worker': 'Maintenance, Facilities, and Trades',
    'System Service Worker 141': 'Maintenance, Facilities, and Trades',
    'System Service Worker PT': 'Maintenance, Facilities, and Trades',
    'Tool Room Attendant': 'Maintenance, Facilities, and Trades',
    'Track Equipment Operator': 'Maintenance, Facilities, and Trades',
    'Track Fore Worker': 'Maintenance, Facilities, and Trades',
    'Track Welder': 'Maintenance, Facilities, and Trades',
    'Track Worker': 'Maintenance, Facilities, and Trades',
    'Transit Vehicle Mechanic': 'Maintenance, Facilities, and Trades',
    'Utility Fore Worker': 'Maintenance, Facilities, and Trades',
    'Utility Worker': 'Maintenance, Facilities, and Trades',
    'Utility Worker PT': 'Maintenance, Facilities, and Trades',
    'Vehicle Inspector': 'Maintenance, Facilities, and Trades',
    'Wayside Inspector': 'Maintenance, Facilities, and Trades',
    'Assistant Logistics Program Manager': 'Maintenance, Facilities, and Trades',
    'Assistant Superintendent Of Way & Facilities': 'Maintenance, Facilities, and Trades',
    'Auto & Equipment Fore worker': 'Maintenance, Facilities, and Trades',
    'Auto & Equipment Maintenance Supervisor': 'Maintenance, Facilities, and Trades',
    'Auto & Equipment Mechanic': 'Maintenance, Facilities, and Trades',
    'Communications Fore worker': 'Maintenance, Facilities, and Trades',
    'Dum Rolling Stock Fore worker': 'Maintenance, Facilities, and Trades',
    'Manager Of Maintenance Plan & Logistics': 'Maintenance, Facilities, and Trades',
    'Manager. Of Auto & Equipment Maintenance': 'Maintenance, Facilities, and Trades',
    'Power & Mechanical Fore Worker': 'Maintenance, Facilities, and Trades',
    'Power & Mechanical Worker': 'Maintenance, Facilities, and Trades',
    'Sect Manager Power & Mech Maintenance': 'Maintenance, Facilities, and Trades',
    'Sect Manager Struct Insp & Maintenance': 'Maintenance, Facilities, and Trades',
    'Senior Manager Of RS&S Ops Admin': 'Maintenance, Facilities, and Trades',
    'Superintendent Of Power & Mech Maintenance': 'Maintenance, Facilities, and Trades',
    'Superintendent Of Rolling Stock & Shops': 'Maintenance, Facilities, and Trades',
    'Superintendent Of Way & Facilities': 'Maintenance, Facilities, and Trades',

    # Planning, Projects, and Infrastructure
    'Asset Coordinator': 'Planning, Projects, and Infrastructure',
    'Asset Data Manager': 'Planning, Projects, and Infrastructure',
    'District Architect': 'Planning, Projects, and Infrastructure',
    'District Right Of Way Surveyor': 'Planning, Projects, and Infrastructure',
    'Group Manager. Engineering': 'Planning, Projects, and Infrastructure',
    'Group Manager., Capital Projects': 'Planning, Projects, and Infrastructure',
    'Group Manager., Integration Eng': 'Planning, Projects, and Infrastructure',
    'Group Manager., Policy Planning': 'Planning, Projects, and Infrastructure',
    'Group Manager. Production Support': 'Planning, Projects, and Infrastructure',
    'Group Manager. Rail Vehicle Cap Program': 'Planning, Projects, and Infrastructure',
    'Group Manager., Station Planning': 'Planning, Projects, and Infrastructure',
    'Group Manager. Sustainability Program': 'Planning, Projects, and Infrastructure',
    'Group Manager. Systems Engineer': 'Planning, Projects, and Infrastructure',
    'Group Manager., Transit Oriented Development': 'Planning, Projects, and Infrastructure',
    'Group Manager. Project Controls': 'Planning, Projects, and Infrastructure',
    'Manager Of Land Use Planning': 'Planning, Projects, and Infrastructure',
    'Manager Of Planning': 'Planning, Projects, and Infrastructure',
    'Manager Of Program Planning Sppt': 'Planning, Projects, and Infrastructure',
    'Manager Of Rail Planning, Link21': 'Planning, Projects, and Infrastructure',
    'Manager Of Strategic Project Suppt': 'Planning, Projects, and Infrastructure',
    'Manager Of Sustainability Projects': 'Planning, Projects, and Infrastructure',
    'Manager. Of Capital Project Control': 'Planning, Projects, and Infrastructure',
    'Manager. Of Capital Project Support': 'Planning, Projects, and Infrastructure',
    'Manager. Of Construction Services': 'Planning, Projects, and Infrastructure',
    'Manager. Of Engineering Liaison': 'Planning, Projects, and Infrastructure',
    'Manager. Of Engineering Programs': 'Planning, Projects, and Infrastructure',
    'Manager. Of Environmental Review': 'Planning, Projects, and Infrastructure',
    'Manager. Of Energy': 'Planning, Projects, and Infrastructure',
    'Manager. Of Eeco Programs': 'Planning, Projects, and Infrastructure',
    'Manager Of Logistics': 'Planning, Projects, and Infrastructure',
    'Manager Of Quality Assurance': 'Planning, Projects, and Infrastructure',
    'Manager Of Sys Capacity Planning': 'Planning, Projects, and Infrastructure',
    'Operations Planner': 'Planning, Projects, and Infrastructure',
    'Parking Coordinator': 'Planning, Projects, and Infrastructure',
    'Principal Landscape Architect': 'Planning, Projects, and Infrastructure',
    'Principal Planner': 'Planning, Projects, and Infrastructure',
    'Principal Performance Analyst': 'Planning, Projects, and Infrastructure',
    'Principal Reliability Engineer': 'Planning, Projects, and Infrastructure',
    'Project Control Administrator': 'Planning, Projects, and Infrastructure',
    'Project Controls Manager': 'Planning, Projects, and Infrastructure',
    'Reliability Analyst': 'Planning, Projects, and Infrastructure',
    'Senior Eeco Analyst': 'Planning, Projects, and Infrastructure',
    'Senior Manager Of Agreement Management': 'Planning, Projects, and Infrastructure',
    'Senior Manager Of Engineering Programs': 'Planning, Projects, and Infrastructure',
    'Senior Planner': 'Planning, Projects, and Infrastructure',
    'Senior Quality Administrator': 'Planning, Projects, and Infrastructure',
    'Senior Quality Manager': 'Planning, Projects, and Infrastructure',
    'Senior Reliability Engineer': 'Planning, Projects, and Infrastructure',
    'Spec Project Manager Maintenance and Const': 'Planning, Projects, and Infrastructure',
    'Vehicle Performance Analyst': 'Planning, Projects, and Infrastructure',
    'Warranty Administrator': 'Planning, Projects, and Infrastructure',
    'Manager Of Warranty Administration': 'Planning, Projects, and Infrastructure',
    'Principal Research Project Analyst': 'Planning, Projects, and Infrastructure',
    'Property Manager': 'Planning, Projects, and Infrastructure',
    'Principal Right Of Way Officer': 'Planning, Projects, and Infrastructure',
    'Quality Team Leader': 'Planning, Projects, and Infrastructure',
    'Spec Project Manager Maintenance & Const': 'Planning, Projects, and Infrastructure',

    # Procurement, Inventory, and Supply Chain
    'Assistant Buyer': 'Procurement, Inventory, and Supply Chain',
    'Buyer': 'Procurement, Inventory, and Supply Chain',
    'Director Of Procurement': 'Procurement, Inventory, and Supply Chain',
    'Expeditor/Clerk': 'Procurement, Inventory, and Supply Chain',
    'Manager Of Acquisition Support': 'Procurement, Inventory, and Supply Chain',
    'Manager Of Inventory Management': 'Procurement, Inventory, and Supply Chain',
    'Manager Of Logistics': 'Procurement, Inventory, and Supply Chain',
    'Manager Of Purchasing': 'Procurement, Inventory, and Supply Chain',
    'Material Control Analyst': 'Procurement, Inventory, and Supply Chain',
    'Material Control Sys Analyst': 'Procurement, Inventory, and Supply Chain',
    'Material Expeditor': 'Procurement, Inventory, and Supply Chain',
    'Procurement Support Manager': 'Procurement, Inventory, and Supply Chain',
    'Rolling Stock Acquisition Admin': 'Procurement, Inventory, and Supply Chain',
    'Senior Buyer': 'Procurement, Inventory, and Supply Chain',
    'Senior Inventory Control Analyst': 'Procurement, Inventory, and Supply Chain',
    'Manager Of Small Business Sppt Svc': 'Procurement, Inventory, and Supply Chain',

    # Customer Service and Accessibility
    'Customer Service Clerk': 'Customer Service and Accessibility',
    'Customer Service Rep': 'Customer Service and Accessibility',
    'Customer Services Assistant': 'Customer Service and Accessibility',
    'Customer Services Supervisor': 'Customer Service and Accessibility',
    'Director Of Customer Access': 'Customer Service and Accessibility',
    'Fare Programs Administrator': 'Customer Service and Accessibility',
    'Manager. Of Access and Accessible Svc': 'Customer Service and Accessibility',
    'Manager. Of Access Programs': 'Customer Service and Accessibility',
    'Manager. Of Customer Services': 'Customer Service and Accessibility',
    'Project Manager, Accessibility': 'Customer Service and Accessibility',
    'Transit Ambassador': 'Customer Service and Accessibility',
    'Manager. Of Access & Accessible Svc': 'Customer Service and Accessibility',
}

df.insert(4, 'category', df.Position.map(category_map))
df.groupby(['high_paying', 'category']).Position.count().rename('count').to_csv('data/out/jobs.csv')
